package:
  name: "alpaca_kernel"
  version: "0.1.14"

source:
  git_rev: 0.1.14
  git_url: https://github.com/twhoekstra/alpaca_kernel

requirements:
  build:
    - python

  run:
    - python >=3.8
    - matplotlib >=3.4.3
    - numpy >=1.21.2
    
about:
  home: https://github.com/twhoekstra/alpaca_kernel
  license: MIT
  license_family: MIT
  summary: Fork of jupyter_micropython_kernel by goatchurchprime
