package:
  name: "alpaca_kernel"
  version: "0.1.18"

source:
  git_rev: 0.1.18
  git_url: https://github.com/twhoekstra/alpaca_kernel

requirements:
  build:
    - python
    - numpy x.x

  run:
    - python
    - matplotlib >=3.4.3
    - numpy x.x
    - pyserial
    
about:
  home: https://github.com/twhoekstra/alpaca_kernel
  license: MIT
  license_family: MIT
  summary: Fork of jupyter_micropython_kernel by goatchurchprime
